openapi: 3.0.0
info:
  description: This is the swagger for flask_api
  version: 0.1.0
  title: Flask API
servers:
  - url: "localhost:5000/api"
    description: Local development api for flask_api
paths:
  /stores:
    get:
      description: Returns all of the stores in the database
      responses:
        '200':
          description: A list of all the stores in the database
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    store_items:
                      type: array
                      items:
                        properties:
                          name:
                            type: string
                          price:
                            type: string
                          time_stamp:
                            type: string